language: dart
dart:
  # Install the latest stable release
  - stable
branches:
  only:
    - master
services:
  - docker
before_install:
  - docker pull couchdb:latest
  - docker run -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password --name couchdb -p 5984:5984 -d couchdb:latest
  - docker ps -a
script:
  - pub run test

