name: wilt
version: 5.0.0
description: A browser/server based CouchDB client library supporting attachments and change notification.
homepage: https://github.com/shamblett/wilt

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  crypto: "^2.1.3"
  http: "^0.12.1"
  json_object_lite: "^2.1.0"

dev_dependencies:
  test: "^1.14.2"
  pana: "^0.13.5"
  pedantic: "^1.9.0"
  build_runner: "^1.8.0"
  build_test: "^0.10.12+1"
  build_web_compilers: "^2.8.0"
